### ISSUE TITLE
Branch: SignalR not have table Matches and Feeds ?

### ISSUE THREAD

**Issue by meninjanho4788** [asadsahi/AspNetCoreSpa#135]
Dear Asad Sahi !
Could you give me query or how to create 2 table need in Branch: SignalR ? and data in this table
I have one error when run file ServerChat\Core\FeedEngine.cs function UpdateScore();

My Error :  

> System.InvalidCastException occurred
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Storage.Internal.UntypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Server.AUT.Server.Chat.Core.FeedEngine.<UpdateScore>d__4.MoveNext() in D:\Other Test 4\Part 11-aspnetcore-signalr bk2\ReactAli2017\ReactAli2017\Server\AUT\Server\Chat\Core\FeedEngine.cs:line 32

Many thank you.

And other problem when i add config SignalR to my project all API call is run so long and not end http://localhost:5000/api/header/menu/0 ( it have 100 rows data json)
i use Belgrade.Sql.Client library to load data it run not end when i add SignalR

**Comment by asadsahi** [comment]
master has a simple implementation of signalR core now. git this a go.
