### ISSUE TITLE
Can't run dotnet run migratedb seeddb

### ISSUE THREAD

**Issue by beriniwlew** [asadsahi/AspNetCoreSpa#152]
When attempting to run "dotnet run migratedb seeddb", it throws an exception.

Unhandled Exception: System.FormatException: Unrecognized argument format: 'migratedb'.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AspNetCoreSpa.Program.BuildWebHost(String[] args) in E:\Work\AspNetCoreSpa\Program.cs:line 23
   at AspNetCoreSpa.Program.Main(String[] args) in E:\Work\AspNetCoreSpa\Program.cs:line 13

**Comment by kmiskiewicz** [comment]
Try just simple dotnet run without extra parameters or...just run by F5 from visual studio 
If you still have some problems with migrations you can try to delete Migrations folder and add a new one like:
Add-Migration InitialCreate  

After the latest updated I had a problem with login mechanism but when I deleted all migrations, and created a new DB (I use MS SQL) it solved my problem

**Comment by asadsahi** [comment]
@beriniwlew I use command line to generate migrations. Bear in mind that you need to create initial migration based on what sql server you are using. By default this project is pointing to sqllite local db file and the Initial migrations are included in the project.

In order to create a new migration I use:

`dotnet ef migrations add "MigrationNameHere"`

Any migration you create should automatically be applied to the database. Obviously for production you might have different workflows.

If you are still encountering any issues, please share a minimum repo with this issue.

Thanks
