### ISSUE TITLE
dotnet ef database update fail System.Data.SqlClient.SqlException (0x80131904): Column 'Id' in table 'OpenIddictApplications' is of a type that is invalid for use as a key column in an index

### ISSUE THREAD

**Issue by thanhnx94** [asadsahi/AspNetCoreSpa#172]
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (189ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [OpenIddictApplications] (
          [Id] TEXT NOT NULL,
          [ClientId] TEXT NOT NULL,
          [ClientSecret] TEXT NULL,
          [ConcurrencyToken] TEXT NULL,
          [DisplayName] TEXT NULL,
          [PostLogoutRedirectUris] TEXT NULL,
          [RedirectUris] TEXT NULL,
          [Type] TEXT NOT NULL,
          CONSTRAINT [PK_OpenIddictApplications] PRIMARY KEY ([Id])
      );
System.Data.SqlClient.SqlException (0x80131904): Column 'Id' in table 'OpenIddictApplications' is of a type that is invalid for use as a key column in an index.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:f6a561b3-9ba2-48ba-8afc-de6951729035
Error Number:1919,State:1,Class:16
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (189ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [OpenIddictApplications] (
          [Id] TEXT NOT NULL,
          [ClientId] TEXT NOT NULL,
          [ClientSecret] TEXT NULL,
          [ConcurrencyToken] TEXT NULL,
          [DisplayName] TEXT NULL,
          [PostLogoutRedirectUris] TEXT NULL,
          [RedirectUris] TEXT NULL,
          [Type] TEXT NOT NULL,
          CONSTRAINT [PK_OpenIddictApplications] PRIMARY KEY ([Id])
      );
System.Data.SqlClient.SqlException (0x80131904): Column 'Id' in table 'OpenIddictApplications' is of a type that is invalid for use as a key column in an index.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:f6a561b3-9ba2-48ba-8afc-de6951729035
Error Number:1919,State:1,Class:16
infoinfo: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.1-rtm-120 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MaxPoolSize=128 
: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.1-rtm-120 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MaxPoolSize=128 
Done. To undo this action, use 'ef migrations remove'
PM> dotnet ef database update
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\THANH\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
infoinfo: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.1-rtm-120 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MaxPoolSize=128 
: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.0.1-rtm-120 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MaxPoolSize=128 
infoinfo: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
infoinfo: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
infoinfo: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
info: Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20171116231347_Initial'.
info: Microsoft.EntityFrameworkCore.Migrations[20402]
      Applying migration '20171116231347_Initial'.

**Comment by asadsahi** [comment]
@thanhnx94 have you tried deleting existing Migrations folder and create new migrations for sql server first?

**Comment by asadsahi** [comment]
@thanhnx94 closing it for now, but let me know if problem persists.
