### ISSUE TITLE
Google Log In not working

### ISSUE THREAD

**Issue by Trojaner25** [asadsahi/AspNetCoreSpa#182]
I can not log in with Google when I deploy the application (doesnt matter if Debug or Release deploy).
The Google log-in works on local build but it does not work after deploying to production machine.
The localhost and the domain are both whitelisted in the Google Developer Console (http and https).

Log:
```
      Request starting HTTP/1.1 GET http://xxxxxxxxx.com/signin-google?state=xxxxxxx&code=4
/yyyyyyy&authuser=0&session_state=zzzzz&prompt=none
info: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[4]
      Error from RemoteAuthentication: OAuth token endpoint failure: Status: BadRequest;Headers: Vary: X-Origin, Origin, Accept-Encoding
      Date: Tue, 19 Dec 2017 13:48:23 GMT
      Cache-Control: max-age=0, private
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-XSS-Protection: 1; mode=block
      Server: GSE
      Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
      Accept-Ranges: none
      Transfer-Encoding: chunked
      ;Body: {
       "error": "redirect_uri_mismatch",
       "error_description": "Bad Request"
      }
      ;.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NetEscapades.AspNetCore.SecurityHeaders.Infrastructure.CustomHeadersMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Joonasw.AspNetCore.SecurityHeaders.Csp.CspMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

Uncommenting the [signin-google route](https://github.com/asadsahi/AspNetCoreSpa/blob/master/Startup.cs#L119) does not solve the issue and also causes issues with the Steam OAuth login.

**Comment by asadsahi** [comment]
@Trojaner25 does google allow you to have multiple domains and callback urls against same application. For production I have seperate google app created with its own domain and callback and it works fine.

**Comment by Trojaner25** [comment]
Thanks for the fast response.
I will try and report back

**Comment by Trojaner25** [comment]
I have set up a new google app (removed the domain from the other app) but I still get the same error message

**Comment by asadsahi** [comment]
ahhh, it must be [this line](https://github.com/asadsahi/AspNetCoreSpa/blob/master/Server/SeedDbData.cs#L108) then. Better if this is a configuration coming from appsettings.json as well. I will update that. But meanwhile try by changing this. Note, if you have already seeded the database, you need to update your datastore accordingly.

**Comment by pvagnini** [comment]
Hi Asadsahi, I think this may be related to my issue #180 where I posted the problem and the fix.

Regards

**Comment by asadsahi** [comment]
@Trojaner25 @pvagnini  This setting is in appsettings.json and appsettings.Development.json based on which environment you are configuring. also, [this](https://github.com/asadsahi/AspNetCoreSpa/commit/505e47a6a3145802d15c46ab70a6a84fee3afc1c) should fix  couple of other issue. Let me know if you find any other issues.
