### ISSUE TITLE
error in run

### ISSUE THREAD

**Issue by daliri72** [asadsahi/AspNetCoreSpa#267]
when I run the project in AspNetCoreSpa.Web directory with` dotnet-run` show this error.
What's the problem? How can I solve this problem?
`s permissions.'.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address https://localhost:5005.
 ---> System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions.) (An attempt was made to access a socket in a way forbidden by its access permissions.)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)  
`

**Comment by daliri72** [comment]
I find problem
I've changed port number 5005 to 5006

**Comment by asadsahi** [comment]
Sometimes dotnet process does not cleanup the port. Try finding that process in task manager and kill it might resolve it.
