### ISSUE TITLE
Error: Cannot find file: "coverage/coverage.json"

### ISSUE THREAD

**Issue by Ketrex** [asadsahi/AspNetCoreSpa#45]
Running on Windows 10, Node 6.9.2, NPM 3.10.9.
Cloned the repo and followed installation instructions with no problem.  When I run the 'npm run test' command, it produces the following output and errors out:

```
F:\github\asadsahi\AspNetCoreSpa>npm run test

aspnetnetcore@0.0.0 pretest F:\github\asadsahi\AspNetCoreSpa
npm run lint

aspnetnetcore@0.0.0 lint F:\github\asadsahi\AspNetCoreSpa
npm run tslint "Client/**/*.ts"

aspnetnetcore@0.0.0 tslint F:\github\asadsahi\AspNetCoreSpa
tslint "Client/**/*.ts"

aspnetnetcore@0.0.0 test F:\github\asadsahi\AspNetCoreSpa
karma start

START:

webpack: bundle is now VALID.
webpack: bundle is now INVALID.

[at-loader] Using typescript@2.1.4 from typescript and "tsconfig.json" from F:\github\asadsahi\AspNetCoreSpa/tsconfig.json.

[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.751 sec.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
config/spec-bundle.js (9.34 MB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
config/spec-bundle.js (9.34 MB)
config/spec-bundle.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
webpack: bundle is now VALID.
03 01 2017 12:12:48.201:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
03 01 2017 12:12:48.203:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
03 01 2017 12:12:48.376:INFO [launcher]: Starting browser PhantomJS
03 01 2017 12:12:49.814:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#bOpsUzgrVTxxWcz_AAAA with id 15427442
  Component: Animation
    √ should create an instance
  Component: ExamplesHome
    √ should create an instance
  Component: Examples
    √ should create an instance
  Component: Typeahead
    √ should create an instance
  Login Model
    √ has email
    √ has password
    √ has rememberMe
  Register Model
    √ has email
    √ has password
    √ has username
  Component: PageNotFound
    √ should create an instance
  x-large directive
    √ should sent font-size to x-large
  User Model
    √ has displayName
    √ has displayName
  Pipe appfUppercase
    √ transforms "abc" to "ABC"
    √ transforms "abc def" to "ABC DEF"
    √ leaves "ABC DEF" unchanged

Finished in 0.031 secs / 0.246 secs

SUMMARY:
√ 17 tests completed

> aspnetnetcore@0.0.0 posttest F:\github\asadsahi\AspNetCoreSpa
> npm run coverage


> aspnetnetcore@0.0.0 coverage F:\github\asadsahi\AspNetCoreSpa
> npm run coverage:remap && npm run coverage:report


> aspnetnetcore@0.0.0 coverage:remap F:\github\asadsahi\AspNetCoreSpa
> remap-istanbul -i coverage/coverage.json -o coverage/coverage.json -t json -e node_modules

Error: Cannot find file: "coverage/coverage.json"
    at readJSON (F:\github\asadsahi\AspNetCoreSpa\node_modules\remap-istanbul\lib\loadCoverage.js:27:10)
    at F:\github\asadsahi\AspNetCoreSpa\node_modules\remap-istanbul\lib\loadCoverage.js:41:18
    at Array.forEach (native)
    at loadCoverage (F:\github\asadsahi\AspNetCoreSpa\node_modules\remap-istanbul\lib\loadCoverage.js:40:11)
    at F:\github\asadsahi\AspNetCoreSpa\node_modules\remap-istanbul\bin\remap-istanbul:118:38
    at main (F:\github\asadsahi\AspNetCoreSpa\node_modules\remap-istanbul\bin\remap-istanbul:117:9)
    at Object.<anonymous> (F:\github\asadsahi\AspNetCoreSpa\node_modules\remap-istanbul\bin\remap-istanbul:163:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

> aspnetnetcore@0.0.0 coverage:report F:\github\asadsahi\AspNetCoreSpa
> istanbul report

Done
```
The actual coverage/coverage.json file is generated, but it only contains brackets `{}` and nothing more.

**Comment by asadsahi** [comment]
@Ketrex I have this fixed in jwt branch of this project. That branch is WIP for jwt and some improvements to the project overall. Once that stabilises, I will merge that into master.

**Comment by asadsahi** [comment]
this should be fixed now as JWT branch is merged in master which includes alot of changes and fixes.
