### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by utilitydelta** [asadsahi/AspNetCoreSpa#49]
Hi,

I just cloned your repo. Went through the steps in the readme. Hit F5. Got the following error under configure() where webpackdevmiddleware is registered.

System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred. (Call to Node module failed with error: TypeError: Cannot read property '0' of undefined
    at ExternalModuleFactoryPlugin.<anonymous> (C:\Users\tyson\Source\Repos\AspNetCoreSpa\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:18:38)
    at C:\Users\tyson\node_modules\webpack\lib\NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\tyson\node_modules\tapable\lib\Tapable.js:75:69)
    at NormalModuleFactory.create (C:\Users\tyson\node_modules\webpack\lib\NormalModuleFactory.js:144:8)
    at C:\Users\tyson\node_modules\webpack\lib\Compilation.js:214:11
    at C:\Users\tyson\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\tyson\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\tyson\node_modules\async\lib\async.js:209:22)
    at Compilation.addModuleDependencies (C:\Users\tyson\node_modules\webpack\lib\Compilation.js:185:8)
    at Compilation.processModuleDependencies (C:\Users\tyson\node_modules\webpack\lib\Compilation.js:170:7))
  Source=System.Private.CoreLib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
       at AspNetCoreSpa.Startup.<Configure>d__7.MoveNext() in C:\Users\tyson\Source\Repos\AspNetCoreSpa\Startup.cs:line 162
  InnerException: 
       HResult=-2146233088
       Message=Call to Node module failed with error: TypeError: Cannot read property '0' of undefined
    at ExternalModuleFactoryPlugin.<anonymous> (C:\Users\tyson\Source\Repos\AspNetCoreSpa\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:18:38)
    at C:\Users\tyson\node_modules\webpack\lib\NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\tyson\node_modules\tapable\lib\Tapable.js:75:69)
    at NormalModuleFactory.create (C:\Users\tyson\node_modules\webpack\lib\NormalModuleFactory.js:144:8)
    at C:\Users\tyson\node_modules\webpack\lib\Compilation.js:214:11
    at C:\Users\tyson\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\tyson\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\tyson\node_modules\async\lib\async.js:209:22)
    at Compilation.addModuleDependencies (C:\Users\tyson\node_modules\webpack\lib\Compilation.js:185:8)
    at Compilation.processModuleDependencies (C:\Users\tyson\node_modules\webpack\lib\Compilation.js:170:7)
       Source=Microsoft.AspNetCore.NodeServices
       StackTrace:
            at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
       InnerException: 

Any tips to fix?
Cheers
Tyson

**Comment by asadsahi** [comment]
@utilitydelta did npm install happened successfully? Can you try removing node_modules folder and try npm install again to see if it fixes the issue?
