### ISSUE TITLE
Live demo is not working

### ISSUE THREAD

**Issue by alaa9jo** [asadsahi/AspNetCoreSpa#66]
I tried to visit the live demo but all I see is an empty page:
http://aspnetcorespa.azurewebsites.net/

In console I see a lot of errors:

````
http://aspnetcorespa.azurewebsites.net/dist/vendor.css Failed to load resource: the server responded with a status of 404 (Not Found)
main.0c9ed59d60e68396ba1f.bundle.js:21 EXCEPTION: The selector "appc-app" did not match any elements
t.handleError @ main.0c9ed59d60e68396ba1f.bundle.js:21
main.0c9ed59d60e68396ba1f.bundle.js:21 ORIGINAL STACKTRACE:
t.handleError @ main.0c9ed59d60e68396ba1f.bundle.js:21
main.0c9ed59d60e68396ba1f.bundle.js:21 Error: The selector "appc-app" did not match any elements
    at d (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:8155)
    at t.selectRootElement (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:16:25026)
    at C (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:8181)
    at proxyViewClass.View_t_Host0.createInternal (/t/t/host.ngfactory.js:12:16)
    at proxyViewClass.t.createHostView (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:31:18200)
    at t.create (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:30530)
    at e.bootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:11974)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9987
    at Array.forEach (native)
    at e._moduleDoBootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9958)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9284
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13450)
    at Object.onInvoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:15806)
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13390)
    at e.run (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10311)
t.handleError @ main.0c9ed59d60e68396ba1f.bundle.js:21
main.0c9ed59d60e68396ba1f.bundle.js:39 Unhandled Promise rejection: The selector "appc-app" did not match any elements ; Zone: <root> ; Task: Promise.then ; Value: Error: The selector "appc-app" did not match any elements
    at d (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:8155)
    at t.selectRootElement (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:16:25026)
    at C (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:8181)
    at proxyViewClass.View_t_Host0.createInternal (/t/t/host.ngfactory.js:12:16)
    at proxyViewClass.t.createHostView (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:31:18200)
    at t.create (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:30530)
    at e.bootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:11974)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9987
    at Array.forEach (native)
    at e._moduleDoBootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9958)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9284
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13450)
    at Object.onInvoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:15806)
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13390)
    at e.run (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10311) Error: The selector "appc-app" did not match any elements
    at d (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:8155)
    at t.selectRootElement (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:16:25026)
    at C (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:8181)
    at proxyViewClass.View_t_Host0.createInternal (/t/t/host.ngfactory.js:12:16)
    at proxyViewClass.t.createHostView (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:31:18200)
    at t.create (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:30530)
    at e.bootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:11974)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9987
    at Array.forEach (native)
    at e._moduleDoBootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9958)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9284
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13450)
    at Object.onInvoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:15806)
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13390)
    at e.run (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10311)
i @ main.0c9ed59d60e68396ba1f.bundle.js:39
main.0c9ed59d60e68396ba1f.bundle.js:39 Error: Uncaught (in promise): Error: The selector "appc-app" did not match any elements
Error: The selector "appc-app" did not match any elements
    at d (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:8155)
    at t.selectRootElement (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:16:25026)
    at C (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:8181)
    at proxyViewClass.View_t_Host0.createInternal (/t/t/host.ngfactory.js:12:16)
    at proxyViewClass.t.createHostView (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:31:18200)
    at t.create (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:30530)
    at e.bootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:11974)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9987
    at Array.forEach (native)
    at e._moduleDoBootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9958)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9284
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13450)
    at Object.onInvoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:15806)
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13390)
    at e.run (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10311)
    at d (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:8155)
    at t.selectRootElement (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:16:25026)
    at C (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:8181)
    at proxyViewClass.View_t_Host0.createInternal (/t/t/host.ngfactory.js:12:16)
    at proxyViewClass.t.createHostView (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:31:18200)
    at t.create (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:30530)
    at e.bootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:11974)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9987
    at Array.forEach (native)
    at e._moduleDoBootstrap (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9958)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:15:9284
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13450)
    at Object.onInvoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:11:15806)
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13390)
    at e.run (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10311)
    at d (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:8155)
    at p (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:7580)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:7288
    at t.invoke (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:13450)
    at e.run (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10311)
    at http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:7952
    at t.invokeTask (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:14127)
    at e.runTask (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:10929)
    at o (http://aspnetcorespa.azurewebsites.net/dist/main.0c9ed59d60e68396ba1f.bundle.js?v=4jtdZ_ic3qOwE4n6ZeMcF1VFvYxdN9Jczh28D-gBs88:39:6998)
i @ main.0c9ed59d60e68396ba1f.bundle.js:39
vendor.css Failed to load resource: the server responded with a status of 404 (Not Found)
````

**Comment by asadsahi** [comment]
up now.
